# Generated by Django 5.0.3 on 2024-03-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mind_ch_db', '0006_rename_user_id_memo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='user',
            new_name='user_id',
        ),
    ]
